name: Scan changed files for ReDoS vulnerabilities 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      vrd:
        image: mdenzo/vuln-regex-detector:1.0.0
      steps:
        - name: Test env
          run: |
            pwd
            ls
            printenv