name: Scan changed files for ReDoS vulnerabilities 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm init --yes

      - uses: actions/checkout@v2
        with: 
          fetch-depth: '0'
      - name: Run entrypoint.sh
        run: |
          echo 'Hello, World!'
          git show --name-only --pretty=format: