name: Vulnerable regex detector

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run entrypoint.sh
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_BASE_REF
          echo $GITHUB_HEAD_REF
          git diff-tree --no-commit-id -r $GITHUB_SHA
          git diff "$GITHUB_BASE_REF".."$GITHUB_HEAD_REF"