name: Vulnerable regex detector

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: '0'

      - name: Run entrypoint.sh
        run: |
          echo $GITHUB_SHA
          git diff --name-only HEAD^ HEAD
          git diff-tree --no-commit-id -r $GITHUB_SHA
          git show --name-only --pretty=format:
        shell: bash