name: Scan changed files for ReDoS vulnerabilities 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v1

        - name: Scan changed files
          run: |
            CHANGED_FILES=`git diff --name-only HEAD^ HEAD | grep -v "^src/validate*\|^.git*"`
            echo $CHANGED_FILES
            mkdir -p changed-files
            echo `pwd`
            echo `ls`

            for i in ${CHANGED_FILES}
              do
                echo $i
                cd changed-files
                echo `pwd`
                rsync -a $i .
                cd ..
              done

            git clone davisjam/vuln-regex-detector
            docker build -t vrd:latest ./vuln-regex-detector/.
            docker run -tpvd changed-files:app/changed-files --name vrd:latest
            docker exec --name vrd:latest "apt install -y jq"

            for i in ${CHANGED_FILES}
              do
                echo '{"file":"./changed-files/'$i'"}' > changed-files/repo.json;    
                docker exec vrd:latest "perl ./bin/check-file.pl ./changed-files/repo.json > repo-out.json ; cat repo-out.json | jq -r '.vulnRegexes'"
              done
