name: Vulnerable regex detector

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run entrypoint.sh
        run: |
          git log
          git diff-tree --no-commit-id --name-only -r GITHUB_SHA
