name: Scan changed files for ReDoS vulnerabilities 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      vrd:
        image: mdenzo/vuln-regex-detector:1.0.0
        ports:
          - 5432/tcp

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm init --yes

      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
        env:
          VULN_REGEX_DETECTOR_ROOT: ${{ jobs.service.vrd.ports[5432] }}
          
      - name: Run entrypoint.sh
        run: |
          sh entrypoint.sh