name: container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: mdenzo/vuln-regex-detector:1.0.0
    steps:
         - name: Test env
           run: |
             node -v
             pwd
             ls
             printenv