name: Vulnerable regex detector

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run entrypoint.sh
        run: |
          git log
          git diff --name-only HEAD^ HEAD
          sh ./entrypoint.sh
